task = "test_run_lss"
[logger]
filename = "deploy"
name = "Deploy"

[model]
"@name" = "dqn_v2"
model_path = "/home/hojechun/github_repos/RLVacDiffSim/data/model_trained"
[model.params]
alpha = 0.0
beta = 1.0
dqn = true

[deploy]
horizon = 10
mode = "lss"
n_episodes = 2
n_poscars = 100
poscar_dir = "/home/hojechun/ssd_mnt/1-RLVacDiff/0-Poscars/POSCARs_256_1_defect"
relax_accuracy = 0.01
temperature = 900

[deploy.input_params]
T_end = 700
T_start = 1200
annealing_time = 3

[deploy.calc_info]
cutoff = 4.0
device = "cuda"
max_iter = 10
platform = "mace"
relax_log = "relax.log"
