task = "test_run_tks"
[logger]
filename = "deploy"
name = "Deploy"

[model]
"@name" = "dqn_v2"
model_path = "/home/hojechun/github_repos/RLVacDiffSim/data/model_trained"
[model.params]
alpha = 1.0
beta = 0.0
dqn = false

[deploy]
horizon = 10
mode = "tks"
n_episodes = 2
n_poscars = 100
poscar_dir = "/home/hojechun/ssd_mnt/1-RLVacDiff/0-Poscars/POSCARs_256_1_defect"
[deploy.simulation_params]
temperature = 900

[deploy.calc_info]
cutoff = 4.0
device = "cuda"
max_iter = 10
platform = "mace"
relax_accuracy = 0.01
relax_log = "relax.log"
