task = "gen_time_dataset_test"
[logger]
filename = "deploy"
name = "Deploy"

[model]
"@name" = "dqn_v2"
model_path = "/home/hojechun/github_repos/RLVacDiffSim/data/model_trained"
[model.params]
alpha = 1.0
beta = 0.0
dqn = false

[deploy]
horizon = 5
mode = "tks"
n_episodes = 2
[deploy.simulation_params]
temperature = 900

[deploy.calc_info]
cutoff = 4.0
device = "cuda"
max_iter = 10
platform = "mace"
relax_accuracy = 0.07
relax_log = "relax.log"
