task = "train_test_context_bandit"
[logger]
filename = "train"
name = "TRAIN"

[model]
"@name" = "dqn_v2"
n_emb = 16
n_feat = 32
[model.params]
alpha = 1.0
beta = 0.0
dqn = false
[model.reaction_model]
"@name" = "painn"
model_path = "/path/to/reaction_model"

[train]
horizon = 3
lr = 1e-5
mode = "context_bandit"
n_episodes = 5
n_poscars = [100]
poscar_dir = ["/path/to/poscars"] # Change this to the directory where your POSCAR files are stored.
temperature = 900
train_all = true
[train.update_params]
batch_size = 8
device = "cuda"
num_epoch = 5

[train.calc_info]
cutoff = 4.0
device = "cuda"
max_iter = 10
platform = "mace"
relax_accuracy = 0.07
relax_log = "relax.log"
