task = "train_test_dqn"
[logger]
filename = "train.log"
name = "TRAIN"

[model]
"@name" = "dqn_v2"
n_emb = 16
n_feat = 32
[model.params]
alpha = 0.0
beta = 1.0
dqn = true
[model.reaction_model]
"@name" = "painn"
model_path = "/home/hojechun/ssd_mnt/1-RLVacDiff/1-Models/best_model_mace_Vrandom_sum_0716.pth.tar"

[train]
horizon = 3
lr = 1e-5
mode = "dqn"
n_episodes = 5
n_poscars = [100]
poscar_dir = ["/home/hojechun/ssd_mnt/1-RLVacDiff/0-Poscars/POSCARs_256_1_defect"]
relax_accuracy = 0.01
temperature = 900
train_all = false
[train.update_params]
batch_size = 8
device = "cuda"
gamma = 0.9
size = 1

[train.calc_info]
cutoff = 4.0
device = "cuda"
max_iter = 10
platform = "mace"
relax_log = "relax.log"
